-- Create, edit, delete and restore ledger transactions in one database
-- transaction each: header, legs, the month if it does not exist yet, and the
-- opening balances from the earliest affected month on. Either all of it is
-- written or none.
--
-- save_ledger_transaction(p_header, p_legs, p_id): without p_id it creates; with
-- a transaction id it replaces that transaction's header and legs. Returns the
-- transaction id. The app still converts currencies: legs arrive with their
-- base amounts and rates. Checks:
--   - income/expense/correction: exactly one leg; income positive, expense
--     negative, correction non-zero; a category for income and expense; no
--     fee. A category, when given, is the caller's.
--   - transfer: two legs on two different accounts, the source negative and
--     the destination positive, 0 <= fee < source; between accounts in the
--     same currency the destination receives exactly source - fee, to the
--     currency's decimals.
--   - every leg: an account of the caller, a positive rate, a base amount with
--     the amount's sign. The leg currency is the account's.
--   - an edit keeps the type and cannot touch a correction generated by an
--     investment.
--
-- set_ledger_transaction_deleted(p_id, p_deleted): soft delete or restore.
-- Corrections generated by investments and debt payments are managed from
-- their own screens.
--
-- transactions.fee widens to 8 decimals so a crypto fee is stored as charged.
--
-- Rollback:
--   DROP FUNCTION public.set_ledger_transaction_deleted(uuid, boolean);
--   DROP FUNCTION public.save_ledger_transaction(jsonb, jsonb, uuid);
--   (fee stays numeric(18, 8): narrowing it back would round stored fees.)
-- destructive-ok: fee goes from numeric(18,4) to numeric(18,8), which keeps every stored value.

ALTER TABLE public.transactions ALTER COLUMN fee TYPE numeric(18, 8);

CREATE OR REPLACE FUNCTION public.save_ledger_transaction(p_header jsonb, p_legs jsonb, p_id uuid DEFAULT NULL)
RETURNS uuid
LANGUAGE plpgsql
AS $$
DECLARE
  v_user uuid := auth.uid();
  v_existing public.transactions;
  v_type public.transaction_type;
  v_date date;
  v_description text := btrim(coalesce(p_header->>'description', ''));
  v_category_id uuid;
  v_fee numeric;
  v_month_id uuid;
  v_rebuild_from uuid;
  v_transaction public.transactions;
  v_leg jsonb;
  v_amount numeric;
  v_base numeric;
  v_rate numeric;
  v_source jsonb;
  v_destination jsonb;
  v_source_currency text;
  v_destination_currency text;
  v_decimals integer;
BEGIN
  IF v_user IS NULL THEN
    RAISE EXCEPTION 'No autenticado' USING ERRCODE = '42501';
  END IF;

  IF p_id IS NOT NULL THEN
    SELECT * INTO v_existing
    FROM public.transactions t
    WHERE t.id = p_id AND t.user_id = v_user AND t.deleted_at IS NULL
    FOR UPDATE;
    IF NOT FOUND THEN
      RAISE EXCEPTION 'Transacción no encontrada';
    END IF;
    IF v_existing.source_investment_id IS NOT NULL OR v_existing.source_investment_sale_id IS NOT NULL THEN
      RAISE EXCEPTION 'Esta corrección está vinculada a una inversión y solo puede editarse modificando la inversión asociada.';
    END IF;
  END IF;

  BEGIN
    v_type := coalesce((p_header->>'transaction_type')::public.transaction_type, v_existing.transaction_type);
    v_date := (p_header->>'date')::date;
    v_category_id := nullif(p_header->>'category_id', '')::uuid;
    v_fee := coalesce(nullif(p_header->>'fee', '')::numeric, 0);
  EXCEPTION WHEN invalid_text_representation OR invalid_datetime_format OR datetime_field_overflow THEN
    RAISE EXCEPTION 'Datos de la transacción inválidos';
  END;
  IF v_type IS NULL OR v_date IS NULL THEN
    RAISE EXCEPTION 'Datos de la transacción inválidos';
  END IF;
  IF p_id IS NOT NULL AND v_type <> v_existing.transaction_type THEN
    RAISE EXCEPTION 'No se puede cambiar el tipo de transacción';
  END IF;
  IF v_description = '' THEN
    RAISE EXCEPTION 'La descripción es obligatoria';
  END IF;
  IF jsonb_typeof(p_legs) IS DISTINCT FROM 'array' THEN
    RAISE EXCEPTION 'Montos inválidos';
  END IF;

  FOR v_leg IN SELECT value FROM jsonb_array_elements(p_legs) LOOP
    v_amount := (v_leg->>'amount')::numeric;
    v_base := (v_leg->>'base_amount')::numeric;
    v_rate := coalesce((v_leg->>'exchange_rate')::numeric, 1);
    IF v_amount IS NULL OR v_amount = 0 OR v_base IS NULL OR v_base = 0 THEN
      RAISE EXCEPTION 'El monto no puede ser 0';
    END IF;
    IF sign(v_amount) <> sign(v_base) THEN
      RAISE EXCEPTION 'El monto base debe tener el mismo signo que el monto';
    END IF;
    IF v_rate <= 0 THEN
      RAISE EXCEPTION 'El tipo de cambio debe ser mayor a 0';
    END IF;
    IF NOT EXISTS (
      SELECT 1 FROM public.accounts a
      WHERE a.id = (v_leg->>'account_id')::uuid AND a.user_id = v_user
    ) THEN
      RAISE EXCEPTION 'Cuenta no encontrada';
    END IF;
  END LOOP;

  IF v_type IN ('income', 'expense', 'correction') THEN
    IF jsonb_array_length(p_legs) <> 1 THEN
      RAISE EXCEPTION 'Solo se permite una línea para ingreso, gasto o corrección';
    END IF;
    v_amount := (p_legs->0->>'amount')::numeric;
    IF v_type = 'income' AND v_amount < 0 THEN
      RAISE EXCEPTION 'Un ingreso tiene que ser positivo';
    END IF;
    IF v_type = 'expense' AND v_amount > 0 THEN
      RAISE EXCEPTION 'Un gasto tiene que ser negativo';
    END IF;
    IF v_type <> 'correction' AND v_category_id IS NULL THEN
      RAISE EXCEPTION 'La categoría es obligatoria';
    END IF;
    IF v_category_id IS NOT NULL AND NOT EXISTS (
      SELECT 1 FROM public.budget_categories c
      WHERE c.id = v_category_id AND c.user_id = v_user
    ) THEN
      RAISE EXCEPTION 'Categoría no encontrada';
    END IF;
    IF v_fee <> 0 THEN
      RAISE EXCEPTION 'Solo una transferencia tiene comisión';
    END IF;
  ELSIF v_type = 'transfer' THEN
    IF jsonb_array_length(p_legs) <> 2 THEN
      RAISE EXCEPTION 'Una transferencia tiene exactamente dos líneas';
    END IF;
    SELECT value INTO v_source FROM jsonb_array_elements(p_legs) WHERE (value->>'amount')::numeric < 0 LIMIT 1;
    SELECT value INTO v_destination FROM jsonb_array_elements(p_legs) WHERE (value->>'amount')::numeric > 0 LIMIT 1;
    IF v_source IS NULL OR v_destination IS NULL THEN
      RAISE EXCEPTION 'Una transferencia sale de una cuenta y entra en otra';
    END IF;
    IF v_source->>'account_id' = v_destination->>'account_id' THEN
      RAISE EXCEPTION 'La cuenta origen y destino deben ser diferentes';
    END IF;
    IF v_fee < 0 OR v_fee >= abs((v_source->>'amount')::numeric) THEN
      RAISE EXCEPTION 'Comisión inválida';
    END IF;
    v_category_id := NULL;

    SELECT a.currency INTO v_source_currency FROM public.accounts a WHERE a.id = (v_source->>'account_id')::uuid;
    SELECT a.currency INTO v_destination_currency FROM public.accounts a WHERE a.id = (v_destination->>'account_id')::uuid;
    IF v_source_currency = v_destination_currency THEN
      SELECT c.decimals INTO v_decimals FROM public.currencies c WHERE c.code = v_source_currency;
      IF round(abs((v_source->>'amount')::numeric) - v_fee, coalesce(v_decimals, 2))
         <> round((v_destination->>'amount')::numeric, coalesce(v_decimals, 2)) THEN
        RAISE EXCEPTION 'En la misma moneda, la cuenta destino recibe exactamente el monto transferido';
      END IF;
    END IF;
  ELSE
    RAISE EXCEPTION 'Tipo de transacción no admitido';
  END IF;

  -- The month of the date, created if missing.
  INSERT INTO public.months (user_id, year, month)
  VALUES (v_user, extract(year FROM v_date)::integer, extract(month FROM v_date)::integer)
  ON CONFLICT (user_id, year, month) DO NOTHING;
  SELECT m.id INTO v_month_id
  FROM public.months m
  WHERE m.user_id = v_user
    AND m.year = extract(year FROM v_date)::integer
    AND m.month = extract(month FROM v_date)::integer;

  IF p_id IS NULL THEN
    INSERT INTO public.transactions (user_id, month_id, category_id, transaction_type, date, description, notes, fee)
    VALUES (
      v_user, v_month_id, v_category_id, v_type, v_date, v_description,
      nullif(btrim(coalesce(p_header->>'notes', '')), ''), v_fee
    )
    RETURNING * INTO v_transaction;
    v_rebuild_from := v_month_id;
  ELSE
    UPDATE public.transactions t
    SET month_id = v_month_id,
        category_id = v_category_id,
        date = v_date,
        description = v_description,
        notes = nullif(btrim(coalesce(p_header->>'notes', '')), ''),
        fee = v_fee,
        updated_at = now()
    WHERE t.id = p_id
    RETURNING * INTO v_transaction;
    DELETE FROM public.transaction_amounts ta WHERE ta.transaction_id = p_id;

    -- The earlier of the old and the new month: both chains change.
    SELECT m.id INTO v_rebuild_from
    FROM public.months m
    WHERE m.id IN (v_existing.month_id, v_month_id)
    ORDER BY m.year, m.month
    LIMIT 1;
  END IF;

  INSERT INTO public.transaction_amounts (transaction_id, account_id, amount, original_currency, exchange_rate, base_amount)
  SELECT
    v_transaction.id,
    a.id,
    (leg.value->>'amount')::numeric,
    a.currency,
    coalesce((leg.value->>'exchange_rate')::numeric, 1),
    (leg.value->>'base_amount')::numeric
  FROM jsonb_array_elements(p_legs) AS leg
  JOIN public.accounts a ON a.id = (leg.value->>'account_id')::uuid;

  PERFORM public.rebuild_opening_balances(v_rebuild_from);

  RETURN v_transaction.id;
END;
$$;

CREATE OR REPLACE FUNCTION public.set_ledger_transaction_deleted(p_id uuid, p_deleted boolean)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
  v_user uuid := auth.uid();
  v_transaction public.transactions;
BEGIN
  IF v_user IS NULL THEN
    RAISE EXCEPTION 'No autenticado' USING ERRCODE = '42501';
  END IF;

  SELECT * INTO v_transaction
  FROM public.transactions t
  WHERE t.id = p_id
    AND t.user_id = v_user
    AND (t.deleted_at IS NULL) = p_deleted
  FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Transacción no encontrada';
  END IF;

  IF p_deleted THEN
    IF v_transaction.source_investment_id IS NOT NULL THEN
      RAISE EXCEPTION 'Esta corrección fue generada por una compra de inversión. Eliminá la inversión para revertirla.';
    END IF;
    IF v_transaction.source_investment_sale_id IS NOT NULL THEN
      RAISE EXCEPTION 'Esta corrección fue generada por una venta de inversión. Eliminá la venta para revertirla.';
    END IF;
    IF EXISTS (SELECT 1 FROM public.debt_activities d WHERE d.transaction_id = p_id) THEN
      RAISE EXCEPTION 'Esta transacción es un pago de deuda. Gestionalo desde la página de Deudas para mantener el saldo consistente.';
    END IF;
  END IF;

  UPDATE public.transactions t
  SET deleted_at = CASE WHEN p_deleted THEN now() ELSE NULL END
  WHERE t.id = p_id;

  IF v_transaction.month_id IS NOT NULL THEN
    PERFORM public.rebuild_opening_balances(v_transaction.month_id);
  END IF;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.save_ledger_transaction(jsonb, jsonb, uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.set_ledger_transaction_deleted(uuid, boolean) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.save_ledger_transaction(jsonb, jsonb, uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.set_ledger_transaction_deleted(uuid, boolean) TO authenticated, service_role;
